### ISSUE TITLE
 This looks good, is this repository being updated occasionally?

### ISSUE THREAD

**Issue by rnjailamba** [Boxx/gokit-base#1]
@boxx

**Comment by bnelz** [comment]
Hi @rnjailamba, I haven't updated this in quite awhile. I have a mirror in my employer's private SCM that may be a bit newer. Are things currently broken? If so, I could spend an hour or two and bring this up to date with the latest version of gokit.

**Comment by rnjailamba** [comment]
HI @Boxx yes it would be great if you can update it with your current developments!
Plus i got this issue after running " ./docker/build.sh -i -v latest" -
```
Building gokit-base container
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /Users/rnjailamba/Desktop/go/src/gokit-base/docker/gokit-base/Dockerfile:no such file or directory
```

**Comment by rnjailamba** [comment]
Bump @Boxx

**Comment by rnjailamba** [comment]
Bump bump @Boxx, let me know if you are busy -> wont bump then :)
